# Generated by Django 5.0.6 on 2024-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.TimeField(blank=True, default='10:00', verbose_name='Время приготовления'),
        ),
    ]
