# Generated by Django 5.0.6 on 2024-05-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_available_alter_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DurationField(blank=True, default='10:00:00', verbose_name='Время приготовления'),
        ),
    ]
