# Generated by Django 5.0.6 on 2024-05-13 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=5), verbose_name='Время приготовления'),
        ),
    ]
